[package]
name = "btle_sniff"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.53", features = ["full"] }
tokio-stream = { version = "0.1.19", features = ["sync"] }
btleplug = "0.12.0"
eframe = { version = "0.35.0", features = [
    "default",
] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"
